In [1]:
print('yoo')

yoo


In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [3]:
type(my_array)

numpy.ndarray

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
for i in np.arange(0,10,2):
    if i in my_array:
        print('heyy')
    else:
        print('sorry for that!')

sorry for that!
heyy
heyy
sorry for that!
sorry for that!


In [10]:
np.zeros(shape=(4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
type(np.zeros(shape=(5,5)))

numpy.ndarray

In [12]:
np.ones(shape=(7,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
np.random.seed(1)
random_arr = np.random.randint(2,10,6)
random_arr

array([7, 5, 6, 2, 9, 3])

In [33]:
random_arr.max()

9

In [34]:
random_arr.argmax()

4

In [35]:
random_arr.min()

2

In [36]:
random_arr.argmin()

3

In [37]:
random_arr.mean()

5.333333333333333

In [39]:
random_arr.argmin()

3

In [41]:
random_arr.shape

(6,)

In [42]:
resized_arr = random_arr.reshape(2,3)
resized_arr

array([[7, 5, 6],
       [2, 9, 3]])

In [48]:
arr1 = np.arange(0,100).reshape(10,10)
arr1
arr2 = np.random.randint(0,100,80).reshape(10,8)
arr2

array([[35, 81, 28, 22, 38, 41, 74, 77],
       [70, 25, 48, 50, 62, 44, 54,  0],
       [86, 16, 19,  9, 92, 51, 10, 68],
       [23, 14, 63, 21, 46,  3, 56, 88],
       [80, 46, 54, 79, 71, 14, 77, 15],
       [25, 53, 84, 58, 85, 29, 44, 37],
       [22, 91, 54, 76, 12, 59, 26, 76],
       [71, 87, 39, 43, 76, 38, 91, 69],
       [98, 33, 43, 26, 56, 69, 73, 52],
       [89, 27, 43,  1, 82, 94, 96, 26]])

In [54]:
arr2[0:5,1:6]

array([[81, 28, 22, 38, 41],
       [25, 48, 50, 62, 44],
       [16, 19,  9, 92, 51],
       [14, 63, 21, 46,  3],
       [46, 54, 79, 71, 14]])

In [55]:
arr2[0:,1].reshape(10,1)

array([[81],
       [25],
       [16],
       [14],
       [46],
       [53],
       [91],
       [87],
       [33],
       [27]])

In [57]:
arr2[0:4,1:]=0
arr2

array([[35,  0,  0,  0,  0,  0,  0,  0],
       [70,  0,  0,  0,  0,  0,  0,  0],
       [86,  0,  0,  0,  0,  0,  0,  0],
       [23,  0,  0,  0,  0,  0,  0,  0],
       [80, 46, 54, 79, 71, 14, 77, 15],
       [25, 53, 84, 58, 85, 29, 44, 37],
       [22, 91, 54, 76, 12, 59, 26, 76],
       [71, 87, 39, 43, 76, 38, 91, 69],
       [98, 33, 43, 26, 56, 69, 73, 52],
       [89, 27, 43,  1, 82, 94, 96, 26]])

In [58]:
arr2

array([[35,  0,  0,  0,  0,  0,  0,  0],
       [70,  0,  0,  0,  0,  0,  0,  0],
       [86,  0,  0,  0,  0,  0,  0,  0],
       [23,  0,  0,  0,  0,  0,  0,  0],
       [80, 46, 54, 79, 71, 14, 77, 15],
       [25, 53, 84, 58, 85, 29, 44, 37],
       [22, 91, 54, 76, 12, 59, 26, 76],
       [71, 87, 39, 43, 76, 38, 91, 69],
       [98, 33, 43, 26, 56, 69, 73, 52],
       [89, 27, 43,  1, 82, 94, 96, 26]])

In [59]:
my_new_arr = arr2.copy()
my_new_arr

array([[35,  0,  0,  0,  0,  0,  0,  0],
       [70,  0,  0,  0,  0,  0,  0,  0],
       [86,  0,  0,  0,  0,  0,  0,  0],
       [23,  0,  0,  0,  0,  0,  0,  0],
       [80, 46, 54, 79, 71, 14, 77, 15],
       [25, 53, 84, 58, 85, 29, 44, 37],
       [22, 91, 54, 76, 12, 59, 26, 76],
       [71, 87, 39, 43, 76, 38, 91, 69],
       [98, 33, 43, 26, 56, 69, 73, 52],
       [89, 27, 43,  1, 82, 94, 96, 26]])

In [61]:
my_new_arr[0:, 1:4] = 0
my_new_arr

array([[35,  0,  0,  0,  0,  0,  0,  0],
       [70,  0,  0,  0,  0,  0,  0,  0],
       [86,  0,  0,  0,  0,  0,  0,  0],
       [23,  0,  0,  0,  0,  0,  0,  0],
       [80,  0,  0,  0, 71, 14, 77, 15],
       [25,  0,  0,  0, 85, 29, 44, 37],
       [22,  0,  0,  0, 12, 59, 26, 76],
       [71,  0,  0,  0, 76, 38, 91, 69],
       [98,  0,  0,  0, 56, 69, 73, 52],
       [89,  0,  0,  0, 82, 94, 96, 26]])

In [62]:
arr2

array([[35,  0,  0,  0,  0,  0,  0,  0],
       [70,  0,  0,  0,  0,  0,  0,  0],
       [86,  0,  0,  0,  0,  0,  0,  0],
       [23,  0,  0,  0,  0,  0,  0,  0],
       [80, 46, 54, 79, 71, 14, 77, 15],
       [25, 53, 84, 58, 85, 29, 44, 37],
       [22, 91, 54, 76, 12, 59, 26, 76],
       [71, 87, 39, 43, 76, 38, 91, 69],
       [98, 33, 43, 26, 56, 69, 73, 52],
       [89, 27, 43,  1, 82, 94, 96, 26]])